# Generated by Django 6.0.2 on 2026-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0007_alter_team_members_alter_worker_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="task_manager.tag"
            ),
        ),
    ]
