# Generated by Django 6.0.2 on 2026-02-13 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0011_alter_task_project_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("is_completed", "name")},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ("username",),
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="task_manager.team",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="task_manager.project",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workers",
                to="task_manager.position",
            ),
        ),
    ]
